[author]
name = "Angel Dhakal"
bio = "software developer passionate about creating efficient and scalable solutions."

[social]
github = "https://github.com/andy4747"
linkedin = "https://linkedin.com/in/angeldhakal"
twitter = "https://x.com/andydl101"

[site]
logo = "/images/logo.png"
favicon = "/favicon.ico"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[permalinks]
  about = "/:filename/"


[params]
  skills = ["Go", "Python", "Node.js", "SQL", "NoSQL", "Docker", "Kubernetes", "CI/CD", "AWS"]
