# SETUP
baseurl = "/"
publishdir = "public"
DefaultContentLanguage = "en"
canonifyUrls = "true"
googleAnalytics = ""
disableKinds = ["RSS","taxonomy","taxonomyTerm"] #remove this if needed
summaryLength = 40

[outputs]
    home = ["HTML","RSS"]
    section  = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "feed"
# For RSS
[author]
    name = "Angel Dhakal"
    email = "angeldhakal97@gmail.com"

pageSize=8
pagePath="page"

[taxonomies]
    tag="tags"

[permalinks]
    blog="blog/:title"

[menu]
  [[menu.main]]
    identifier="home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier="projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier="blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    identifier="about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  skills = ["Go", "Python", "Node.js", "SQL", "NoSQL", "Docker", "Kubernetes", "CI/CD", "AWS"]

