[phases.setup]
nixPkgs = [
    "go",
    "hugo",
    "nodejs",
    "git",
    "python",
]

[phases.build]
commands = [
    "go mod download",
    "npm install",
    "npx tailwindcss -i ./assets/css/main.css -o ./static/css/style.css && npx postcss ./static/css/style.css -o ./static/css/style.css",
    "hugo --gc --minify",
]

[start]
cmd = "python -m http.server 8080"
