[phases.setup]
nixPkgs = [
    "hugo",
    "nodejs"
]

[phases.build]
commands = [
    "npm install",
    "npx tailwindcss -i ./assets/css/main.css -o ./static/css/style.css && npx postcss ./static/css/style.css -o ./static/css/style.css",
    "hugo --gc --minify",
]

[start]
cmd = "npx serve --single public"
